flaskFile/user/routes.py
from flask import url_for, redirect, render_template, flash, request, Blueprint
from flask_login import login_required, current_user, login_user, logout_user
from flaskFile.models import User
from flaskFile import bcrypt
from flaskFile.user.forms import LoginForm

user = Blueprint('user', __name__)

@user.route("/login/<string:ps_id>", methods=['GET', 'POST'])
def login(ps_id: str):
    if current_user.is_authenticated:
        return redirect(url_for('general.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).filter_by(ps_id = ps_id).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful', 'info')
            nextPage = request.args.get('next', 'home')
            return redirect(nextPage)
        else:
            flash('Login Unsuccessful. Please check details', 'danger')
    return render_template('user/login.html', title='Login', form=form)

@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('general.home'))

@user.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    imageFile = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('user/account.html', title=current_user.username, imageFile=imageFile)

flaskFile/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

      {% if title %}
          <title>Powstik- {{ title }}</title>
      {% else %}
          <title>Powstik</title>
      {% endif %}
  </head>
  <body>
      <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Powstik</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                {% endif %}
              </div>
              <div class="navbar-nav">
                  <a class="nav-item nav-link" href="mailto:siddpurwar@gmial.com?cc=siddpurwar@gmial.com&body=Please describe issue in detail, try including screenshots">Contact Us</a>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </main>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>